"""empty message

Revision ID: 8c9a5b2b3ccc
Revises: 310e91f1a9d5
Create Date: 2022-11-15 17:46:28.141898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9a5b2b3ccc'
down_revision = '310e91f1a9d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_reviews',
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('recommendation', sa.Float(), nullable=True),
    sa.Column('positive_reviews', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('review_site_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['review_site_id'], ['review_sites.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'review_site_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games_reviews')
    # ### end Alembic commands ###
