"""empty message

Revision ID: 568afb2b57f3
Revises: aae4fc4f8124
Create Date: 2022-11-15 17:12:49.271628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568afb2b57f3'
down_revision = 'aae4fc4f8124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publishers')
    # ### end Alembic commands ###
